### ISSUE TITLE
fail to run example command `03-spikein_snv_and_indel_Illumina.sh`

### ISSUE THREAD

**Issue by lierhan7** [nccl-jmli/VarBen#11]
Dear Prof. Li,
I got some error message when running the example command `03-spikein_snv_and_indel_Illumina.sh`, could you please help me ? The attachment is the complete log file.
[log.txt](https://github.com/nccl-jmli/VarBen/files/5621268/log.txt)

step3: modify the reads in total_chosen_reads itself
[E::bam_read1] CIGAR and query sequence lengths differ for FCHV3N7BCXY:1:2115:4208:45056#TCACCTCA
samtools sort: truncated file. Aborting
step4: write edited reads to edited file and exclude reads to exclude file ,than remap edited file to reference
remap start .......................................
samtools sort start................................
samtools sort -n -o ../output/illumina/tempDir/edit.sortByName.bam ../output/illumina/tempDir/edit.bam
Traceback (most recent call last):
  File "../../bin/muteditor.py", line 122, in <module>
    run()
  File "../../bin/muteditor.py", line 118, in run
    main(run_args)
  File "../../bin/muteditor.py", line 60, in main
    run_args.alignerIndex, run_args.single)
  File "/home/lierhan/VarBen-master/bin/../varben/deal_mut/readsReplace.py", line 65, in reads_replace
    remap(aligner_index, edit_bam_file, edit_remap_bam_file, aligner, is_single, header=head)
  File "/home/lierhan/VarBen-master/bin/../varben/common/bamconvert.py", line 98, in remap
    bamSort(inBamFile, inPrefix + ".sortByName", sort_key="name")
  File "/home/lierhan/VarBen-master/bin/../varben/common/bamconvert.py", line 78, in bamSort
    _call(bamSort_cmd)
  File "/home/lierhan/VarBen-master/bin/../varben/common/bamconvert.py", line 14, in _call
    raise Exception("Cmd Error: %s" % cmd)
Exception: Cmd Error: samtools sort -n -o ../output/illumina/tempDir/edit.sortByName.bam ../output/illumina/tempDir/edit.bam

Thanks a lot!
Best,
lierhan

**Comment by yulijia** [comment]
Thank you for your feedback.
The old version of EGFR bam file has a problem with wrong duplicated read names. we have submitted a new one in this repo. Please download it and try again.
