### ISSUE TITLE
Four errors happened when run the muteditor.py

### ISSUE THREAD

**Issue by xmy1990** [nccl-jmli/VarBen#25]
hi ，liliya:
when I run "muteditor.py"  on 10 sample bams **from the same sequecer with the same pipeline**,  4 samples finished with the edit.sorted.bam.

But the other 6 bams failed with 4 types of  errors as below:

**The first error**
Traceback (most recent call last):
File "/VarBen-master/bin/muteditor.py", line 122, in <module>
run()
File "/VarBen-master/bin/muteditor.py", line 118, in run
main(run_args)
File "/VarBen-master/bin/muteditor.py", line 45, in main
success_list_file)
File "/VarBen-master/bin/../varben/deal_mut/dealHaplotype.py", line 225, in deal_haplotype_multi
res = each_res.get()
File "/lib/python2.7/multiprocessing/pool.py", line 572, in get
raise self._value
Exception: Cmd Error: samtools sort -n -o /tempDir/haplotype_out/chr5_112175742_112175742.chosen.edited.sortByName.bam /tempDir/haplotype_out/chr5_112175742_112175742.chosen.edited.bam

**The second error**
step4: write edited reads to edited file and exclude reads to exclude file ,than remap edited file to reference
Traceback (most recent call last):
File "/VarBen-master/bin/muteditor.py", line 122, in <module>
run()
File "/VarBen-master/bin/muteditor.py", line 118, in run
main(run_args)
File "/VarBen-master/bin/muteditor.py", line 60, in main
run_args.alignerIndex, run_args.single)
File "/VarBen-master/bin/../varben/deal_mut/readsReplace.py", line 31, in reads_replace
read.query_qualities = my_read.query_qualities
File "pysam/libcalignedsegment.pyx", line 1139, in pysam.libcalignedsegment.AlignedSegment.query_qualities.set (pysam/libcalignedsegment.c:13760)
ValueError: quality and sequence mismatch: 150 != 290

**The third error**
step3: modify the reads in total_chosen_reads itself
[E::bam_read1] CIGAR and query sequence lengths differ for depth8000-chr5-21230627
samtools sort: truncated file. Aborting
step4: write edited reads to edited file and exclude reads to exclude file ,than remap edited file to reference
remap start .......................................
samtools sort start................................
samtools sort -n -o /tempDir/edit.sortByName.bam /tempDir/edit.bam
Traceback (most recent call last):
File "/VarBen-master/bin/muteditor.py", line 122, in <module>
run()
File "/VarBen-master/bin/muteditor.py", line 118, in run
main(run_args)
File "/VarBen-master/bin/muteditor.py", line 60, in main
run_args.alignerIndex, run_args.single)
File "/VarBen-master/bin/../varben/deal_mut/readsReplace.py", line 65, in reads_replace
remap(aligner_index, edit_bam_file, edit_remap_bam_file, aligner, is_single, header=head)
File "/VarBen-master/bin/../varben/common/bamconvert.py", line 98, in remap
bamSort(inBamFile, inPrefix + ".sortByName", sort_key="name")
File "/VarBen-master/bin/../varben/common/bamconvert.py", line 78, in bamSort
_call(bamSort_cmd)
File "/VarBen-master/bin/../varben/common/bamconvert.py", line 14, in _call
raise Exception("Cmd Error: %s" % cmd)
Exception: Cmd Error: samtools sort -n -o /tempDir/edit.sortByName.bam /tempDir/edit.bam

For this error, **I have tried to solve with:**
https://github.com/nccl-jmli/VarBen/issues/24
https://github.com/nccl-jmli/VarBen/issues/18
But，the same error happened.

**The fourth error**
Traceback (most recent call last):
File "/VarBen-master/bin/muteditor.py", line 122, in <module>
run()
File "/VarBen-master/bin/muteditor.py", line 118, in run
main(run_args)
File "/VarBen-master/bin/muteditor.py", line 45, in main
success_list_file)
File "/VarBen-master/bin/../varben/deal_mut/dealHaplotype.py", line 225, in deal_haplotype_multi
res = each_res.get()
File "/lib/python2.7/multiprocessing/pool.py", line 572, in get
raise self._value
Exception: Cmd Error: samtools view -bS /tempDir/haplotype_out/chr5_112175742_112175742.chosen.remap.unsorted.bam

Thank you !

**Comment by xmy1990** [comment]
Hi @https://github.com/AsmaaSamyMohamedMahmoud 
～～～
Thank you

**Comment by xmy1990** [comment]
The above error really bothered me for several days, If any of you could give me some suggestions to fix it, I will be really appreciated. Thanks in advance 

@yulijia  @AsmaaSamyMohamedMahmoud

**Comment by yulijia** [comment]
Hi @xmy1990 ,

Sorry, I couldn't detect the reason without see your datasets and processing command, and I currently don't have time to help you fix this issue. If you don't mind you can post the datasets and command in this thread and i may try to look into it during winter holiday.

**Comment by asmmahmoud** [comment]
Hi @xmy1990  I am sorry I don't know how to solve your four errors except the third one as I had this before and I solved using this command: samtools view -h original.bam | awk '$6 !~ /H/{print}' | samtools view -bS - > noHclips.bam". to remove the hardclip reads. Then run samtools index to index the noHclips.bam then run muteditor.py again. This worked with me.

**Comment by xmy1990** [comment]
Thanks @ AsmaaSamyMohamedMahmoud
 I have tried to solve it as you did, but, the same error happened.
